# API specification
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  autodiscoveryID: "00000000"
  
# call fsOilInfo API
req-fsOilInfo-pro-api:
  host: "localhost"
  port: "8081"
  base-path: "/api/${project.version}"

# call chdSchInfo API
req-chdSchInfo-pro-api:
  host: "localhost"
  port: "8081"
  base-path: "/api/${project.version}"

# call pdpMilInfo API
req-pdpMilInfo-pro-api:
  host: "localhost"
  port: "8081"
  base-path: "/api/${project.version}"

# call custRiskChk API
req-custRiskChk-pro-api:
  host: "localhost"
  port: "8081"
  base-path: "/api/${project.version}"

# call batchInfo sys API
req-dbServer-sys-api:
  host: "localhost"
  port: "8081"
  base-path: "/api/${project.version}"
       
# Common configuration   
connection:
  idle-timeout: "300000"
  frequency: "5000"
  attempts: "2"