# Common properties shared across all environments
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  autodiscoveryID: "00000000"
 
salesforce:
  username: ""
  password: "" 
  token: ""